name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build the app
      run: go build -o main .

    - name: Deploy to EC2
      env:
        EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        scp -o StrictHostKeyChecking=no -i "$EC2_PRIVATE_KEY" main $EC2_USER@$EC2_HOST:/home/$EC2_USER/main
        ssh -o StrictHostKeyChecking=no -i "$EC2_PRIVATE_KEY" $EC2_USER@$EC2_HOST "sudo systemctl restart myapp"
