name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23

    - name: Build the app
      run: go build -o main .

    - name: Deploy to EC2
      env:
        EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        API_BOT_TOKEN: ${{ secrets.API_BOT_TOKEN }}
      run: |
        echo "$EC2_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        
        # Stop the service
        ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST "sudo systemctl stop myapp"
        
        # Wait until the service is confirmed to be stopped
        ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST '
          while systemctl is-active --quiet myapp; do
            echo "Waiting for myapp to stop..."
            sleep 2
          done
          echo "Service myapp has stopped."
        '
        
        # Copy the main binary
        scp -o StrictHostKeyChecking=no -i private_key.pem main $EC2_USER@$EC2_HOST:/home/$EC2_USER/main

        # Copy the images directory
        scp -o StrictHostKeyChecking=no -i private_key.pem -r images $EC2_USER@$EC2_HOST:/home/$EC2_USER/images
        
        # Create a .env file on the EC2 instance and move it to the root directory
        ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST "
          echo 'TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}' > /home/$EC2_USER/.env &&
          echo 'API_BOT_TOKEN=${API_BOT_TOKEN}' >> /home/$EC2_USER/.env &&
          sudo chmod 777 /home/$EC2_USER/.env &&
        "

        # Restart the service
        ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST "sudo systemctl restart myapp"
        
        # Move images directory to root and set permissions
        ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST "sudo cp -r /home/$EC2_USER/images / && sudo chmod -R 777 /images"

        # Clean up
        rm private_key.pem
