name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23

    - name: Build the app
      run: go build -o main .

    - name: Deploy to EC2
      env:
        EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        API_BOT_TOKEN: ${{ secrets.API_BOT_TOKEN }}
        YOUR_PERSONAL_CHAT_ID: ${{ secrets.YOUR_PERSONAL_CHAT_ID }}
      run: |
        echo "$EC2_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        
        # Create app directory if it doesn't exist
        ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST "mkdir -p /home/$EC2_USER/apps/justlittlethings"
        
        # Stop the service
        ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST "sudo systemctl stop justlittlethingsbot"
        
        # Wait until the service is confirmed to be stopped
        ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST '
          while systemctl is-active --quiet justlittlethingsbot; do
            echo "Waiting for justlittlethingsbot to stop..."
            sleep 2
          done
          echo "Service justlittlethingsbot has stopped."
        '
        
        # Copy the main binary
        scp -o StrictHostKeyChecking=no -i private_key.pem main $EC2_USER@$EC2_HOST:/home/$EC2_USER/apps/justlittlethings/main
    
        # Copy the images directory
        scp -o StrictHostKeyChecking=no -i private_key.pem -r images $EC2_USER@$EC2_HOST:/home/$EC2_USER/apps/justlittlethings/images
        
        # Create a .env file on the EC2 instance
        ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST "
          echo 'TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}' > /home/$EC2_USER/apps/justlittlethings/.env &&
          echo 'API_BOT_TOKEN=${API_BOT_TOKEN}' >> /home/$EC2_USER/apps/justlittlethings/.env &&
          echo 'YOUR_PERSONAL_CHAT_ID=${YOUR_PERSONAL_CHAT_ID}' >> /home/$EC2_USER/apps/justlittlethings/.env &&
          sudo chmod 600 /home/$EC2_USER/apps/justlittlethings/.env
        "
    
        # Restart the service
        ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST "sudo systemctl restart justlittlethingsbot"
        
        # Set permissions for the app directory
        ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST "sudo chown -R $EC2_USER:$EC2_USER /home/$EC2_USER/apps/justlittlethings && sudo chmod -R 755 /home/$EC2_USER/apps/justlittlethings"
    
        # Clean up
        rm private_key.pem